/**
 * Deck definitions: front = Hawaiian term, back = English gloss.
 * Surf deck: 100 terms (duplicate ʻōlelo like Kōʻolau / Huki kept as separate cards per your list).
 */
window.DECKS = [
  {
    id: "surf-olelo-1",
    title: "Surf 1",
    subtitle: "Water, waves & voyaging",
    accent: "ocean",
    cards: [
      { front: "Kai", back: "Sea, saltwater (near-shore)" },
      { front: "Moana", back: "Open ocean, deep water" },
      { front: "Wai", back: "Freshwater" },
      { front: "Waikōloa", back: "Raging water" },
      { front: "Kahakai", back: "Beach, shoreline (kaha + kai)" },
      { front: "Kōʻolau", back: "Windward side" },
      { front: "Loko", back: "Pond, pool" },
      { front: "Muliwai", back: "Estuary, river mouth" },
      { front: "Lua", back: "Pit; also used for depth" },
      { front: "Pōʻai kai", back: "Surrounded by sea" },
      { front: "Nui", back: "Great, vast (as in the deep)" },
      { front: "\u0100nuenue", back: "Rainbow (often seen at sea)" },
      { front: "Ua", back: "Rain" },
      { front: "Hau", back: "Dew, ice, snow; cold" },
      { front: "Wai ola", back: "Water of life" },
      { front: "Heʻe nalu", back: "Surfing; literally \"wave sliding\"" },
      { front: "Nalu", back: "Wave, surf" },
      { front: "Papa heʻe nalu", back: "Surfboard" },
      { front: "Kaha nalu", back: "Bodysurfing" },
      { front: "Paipo", back: "Bodyboard (short prone board, ancestor of the boogie board)" },
    ],
  },
  {
    id: "surf-olelo-2",
    title: "Surf 2",
    subtitle: "Water, waves & voyaging",
    accent: "ocean",
    cards: [
      { front: "Pae i ka nalu", back: "To ride a wave to shore, to catch a wave" },
      { front: "Piʻi mai ka nalu", back: "\"Surf's up\"; the waves are mounting" },
      { front: "Alaia", back: "Thin, finless wooden surfboard used historically" },
      { front: "Olo", back: "Long, heavy surfboard, once reserved for royalty" },
      { front: "Heʻe puʻe wai", back: "To surf the mouth of a stream (Hawaiʻi Island)" },
      { front: "Pākākā nalu", back: "Outrigger canoe surfing" },
      { front: "Heʻe umauma", back: "Bodysurfing (chest sliding)" },
      { front: "Poʻina nalu", back: "Shorebreak" },
      { front: "Kalana nalu", back: "Lineup" },
      { front: "Heʻe one", back: "Sand surfing" },
      { front: "Nalu nui", back: "Big wave" },
      { front: "Nalu liʻiliʻi", back: "Small wave" },
      { front: "Poʻina", back: "Breaking wave, shorebreak" },
      { front: "Kai koʻo", back: "Rough sea" },
      { front: "Kai mālie", back: "Calm sea" },
      { front: "Kai hāwanawana", back: "Whispering sea" },
      { front: "ʻAle", back: "Wave, ripple" },
      { front: "ʻAle nui", back: "Large swell" },
      { front: "Hauʻoli nalu", back: "Joyful waves" },
      { front: "Kai ʻēʻē", back: "Rising tide, surging sea" },
    ],
  },
  {
    id: "surf-olelo-3",
    title: "Surf 3",
    subtitle: "Water, waves & voyaging",
    accent: "ocean",
    cards: [
      { front: "Kai hoʻē", back: "Receding sea" },
      { front: "Mimilo", back: "Whirlpool, eddy" },
      { front: "Au", back: "Current, flow" },
      { front: "Au loa", back: "Deep current" },
      { front: "Huki", back: "Pull (as in a rip current)" },
      { front: "ʻAukai", back: "To travel by sea; sailor" },
      { front: "ʻAumoana", back: "To travel on the ocean; sailor" },
      { front: "Holomoana", back: "To sail on the ocean; sailor" },
      { front: "Holokahiki", back: "To sail to foreign lands" },
      { front: "Hoʻokele", back: "Steersman, navigator" },
      { front: "Hoe waʻa", back: "Paddler" },
      { front: "Hoʻomau", back: "Steady as you go; keep it up; persist" },
      { front: "Huli i lalo", back: "Turn downwind" },
      { front: "Huli i luna", back: "Turn upwind" },
      { front: "Kaʻalalo", back: "Sail downwind" },
      { front: "Kaʻaluna", back: "Sail upwind" },
      { front: "Hoʻopahuʻa", back: "To sail windward; move against the wind" },
      { front: "Huki", back: "Pull on a line" },
      { front: "Hoʻopaʻa", back: "Make fast; hold firm; to bind" },
      { front: "Hoʻopae", back: "Go ashore (Hōkūleʻa)" },
    ],
  },
  {
    id: "surf-olelo-4",
    title: "Surf 4",
    subtitle: "Water, waves & voyaging",
    accent: "ocean",
    cards: [
      { front: "Waʻa", back: "Canoe" },
      { front: "Waʻa kaulua", back: "Double-hulled canoe" },
      { front: "Waʻa ʻākea", back: "Wide canoe" },
      { front: "Iako", back: "Crossbeam of an outrigger canoe" },
      { front: "Ama", back: "Outrigger float" },
      { front: "Hoe", back: "Paddle, oar" },
      { front: "Koʻi", back: "Adze (tool for carving canoes)" },
      { front: "Koa", back: "The wood most prized for canoe building" },
      { front: "Pola", back: "The deck or platform between canoe hulls" },
      { front: "Pale", back: "Hull, side of a canoe" },
      { front: "Hōkū", back: "Star" },
      { front: "Hōkūleʻa", back: "Arcturus; the star of gladness (name of the famous voyaging canoe)" },
      { front: "Makani", back: "Wind" },
      { front: "Kōʻolau", back: "Northeast trade wind" },
      { front: "Kona", back: "Leeward; southerly wind" },
      { front: "\u02BB\u0100pana", back: "Direction, bearing" },
      { front: "Lā", back: "Sun" },
      { front: "Mahina", back: "Moon" },
      { front: "Po", back: "Night" },
      { front: "Ao", back: "Day, cloud, world" },
    ],
  },
  {
    id: "surf-olelo-5",
    title: "Surf 5",
    subtitle: "Water, waves & voyaging",
    accent: "ocean",
    cards: [
      { front: "Mano", back: "Shark" },
      { front: "Honu", back: "Sea turtle" },
      { front: "Naiʻa", back: "Dolphin" },
      { front: "Koholā", back: "Humpback whale" },
      { front: "Heʻe", back: "Octopus" },
      { front: "\u02BB\u014cpelu", back: "Mackerel scad (common fish)" },
      { front: "Limu", back: "Seaweed, algae" },
      { front: "ʻOpihi", back: "Limpet (beloved shellfish)" },
      { front: "Pūpū", back: "Shell, shellfish" },
      { front: "Koʻa", back: "Coral, fishing shrine" },
      { front: "Aloha", back: "Love, affection, hello, goodbye" },
      { front: "Mālama", back: "To care for, protect (as in mālama kai — care for the sea)" },
      { front: "Kuleana", back: "Responsibility, right, privilege" },
      { front: "Mana", back: "Spiritual power, authority" },
      { front: "ʻAumākua", back: "Ancestral guardian spirit (often a shark or sea creature)" },
      { front: "Kahuna", back: "Expert master; e.g. master canoe builder" },
      { front: "Aliʻi", back: "Chief, royalty" },
      { front: "Pono", back: "Righteousness, balance, proper" },
      { front: "Haʻaheo", back: "Pride (as in pride of the sea)" },
      { front: "Mahalo", back: "Gratitude, thanks" },
    ],
  },
  {
    id: "tropical-fruits-1",
    title: "Fruits 1",
    subtitle: "Tropical fruit vocabulary",
    accent: "fruit",
    cards: [
      { front: "Banana", back: "Soft, sweet fruit commonly eaten ripe or cooked green" },
      { front: "Papaya", back: "Orange tropical fruit with black seeds and mild sweetness" },
      { front: "Mango", back: "Juicy stone fruit with rich, floral sweetness" },
      { front: "Pineapple", back: "Spiky tropical fruit with bright sweet-tart flavor" },
      { front: "Coconut", back: "Large palm fruit with water and rich white flesh" },
      { front: "Guava", back: "Fragrant fruit with edible seeds and pink or white flesh" },
      { front: "Passionfruit", back: "Aromatic pulp-filled fruit with crunchy edible seeds" },
      { front: "Dragon fruit", back: "Cactus fruit with speckled flesh and mild sweetness" },
      { front: "Lychee", back: "Small, perfumed fruit with translucent juicy flesh" },
      { front: "Rambutan", back: "Hairy-skinned fruit related to lychee and longan" },
      { front: "Longan", back: "Small sweet fruit with clear flesh and dark seed" },
      { front: "Mangosteen", back: "Purple fruit with soft white segments and floral tang" },
      { front: "Soursop", back: "Creamy white fruit with sweet-tart, custard-like flavor" },
      { front: "Starfruit", back: "Crisp fruit that forms a star shape when sliced" },
      { front: "Breadfruit", back: "Starchy tropical fruit often roasted or steamed" },
      { front: "Jackfruit", back: "Huge fruit with fibrous yellow bulbs and sweet aroma" },
      { front: "Durian", back: "Strong-smelling fruit with rich custard-like interior" },
      { front: "Tamarind", back: "Brown pod fruit with sour-sweet sticky pulp" },
      { front: "Sapodilla", back: "Brown fruit with malty, caramel-like sweetness" },
      { front: "Cherimoya", back: "Green fruit with creamy flesh and tropical flavor notes" },
      { front: "Atemoya", back: "Hybrid fruit similar to cherimoya and sugar apple" },
      { front: "Sugar apple", back: "Segmented fruit with very sweet, custardy flesh" },
      { front: "Cacao pod", back: "Fruit pod that contains cacao beans for chocolate" },
      { front: "Acai berry", back: "Dark Amazon berry often used in smoothie bowls" },
      { front: "Cempedak", back: "Southeast Asian fruit related to jackfruit, very aromatic" },
    ],
  },
  {
    id: "tropical-fruits-2",
    title: "Fruits 2",
    subtitle: "Tropical fruit vocabulary",
    accent: "fruit",
    cards: [
      { front: "Salak", back: "Snake fruit with reddish scaly skin and crisp flesh" },
      { front: "Rose apple", back: "Bell-shaped fruit with light floral, watery crunch" },
      { front: "Java plum", back: "Purple fruit with astringent-sweet taste when ripe" },
      { front: "Custard apple", back: "Soft, sweet fruit with creamy white pulp" },
      { front: "Camu camu", back: "Very tart Amazon fruit known for high vitamin C" },
      { front: "Noni", back: "Strong-scented fruit often used in traditional preparations" },
      { front: "Pomegranate", back: "Many-seeded fruit with juicy ruby arils" },
      { front: "Loquat", back: "Small orange fruit with sweet-tart flesh" },
      { front: "Barbados cherry", back: "Also called acerola; tart cherry-like tropical fruit" },
      { front: "Surinam cherry", back: "Ribbed red fruit with resinous sweet-tart flavor" },
      { front: "Canistel", back: "Eggfruit with dense yellow flesh and sweet taste" },
      { front: "Mamey sapote", back: "Large fruit with salmon-orange sweet creamy flesh" },
      { front: "White sapote", back: "Green-yellow fruit with smooth, vanilla-like sweetness" },
      { front: "Black sapote", back: "Dark-fleshed fruit sometimes called chocolate pudding fruit" },
      { front: "Abiu", back: "Yellow fruit with translucent jelly-like sweet flesh" },
      { front: "Lucuma", back: "Peruvian fruit with dry sweet flesh used in desserts" },
      { front: "Feijoa", back: "Pineapple guava with aromatic grainy sweet-tart pulp" },
      { front: "Kiwano", back: "Horned melon with green jelly-like seeded interior" },
      { front: "Santol", back: "Cottony tropical fruit with sweet or sour varieties" },
      { front: "Pulasan", back: "Close relative of rambutan with thicker skin" },
      { front: "Langsat", back: "Small translucent fruit in clusters with sweet acidity" },
      { front: "Bacuri", back: "Brazilian fruit with fragrant white creamy pulp" },
      { front: "Cupuacu", back: "Amazon fruit related to cacao with aromatic sour pulp" },
      { front: "Marang", back: "Soft, aromatic fruit related to jackfruit and breadfruit" },
      { front: "Ice cream bean", back: "Long pod fruit with fluffy sweet cottony pulp" },
    ],
  },
  {
    id: "proverbs-1",
    title: "Proverbs 1",
    subtitle: "Hawaiian idioms and wisdom",
    accent: "ocean",
    cards: [
      {
        front: "Kūlia i ka nuʻu.",
        back: "Strive to reach the highest.\n\nStrive to do your best - Motto of Queen Kapiʻolani.",
      },
      {
        front: "Pūpūkahi i holomua.",
        back: "Unite in order to progress.",
      },
      {
        front: "Ma ka hana ka ʻike.",
        back: "In working one learns.\n\nKnowledge can be acquired by doing.",
      },
      {
        front: "ʻUmia ka hanu.",
        back: "Hold the breath.\n\nBe patient. Don't give up too easily.",
      },
    ],
  },
  {
    id: "proverbs-2",
    title: "Proverbs 2",
    subtitle: "Hawaiian idioms and wisdom",
    accent: "ocean",
    cards: [
      {
        front: "ʻAʻa i ka hula, waiho i ka hilahila i ka hale.",
        back: "When one wants to dance the hula, bashfulness should be left at home.\n\nDon’t be shy. Participate! This does not just pertain to hula.",
      },
      {
        front: "Mai makaʻu i ka hana, makaʻu i ka moloā.",
        back: "Don’t fear work, fear laziness.\n\nDon’t be lazy.",
      },
      {
        front: "Na ka ʻeleu miki.",
        back: "(The prize) goes to the quick one.\n\nSimilar to the saying, “The early bird gets the worm.”",
      },
      {
        front: "ʻAʻohe hana nui ke alu ʻia.",
        back: "No task is too big when done together by all.\n\nIf everyone contributes to the task, it lightens the load.",
      },
    ],
  },
  {
    id: "proverbs-3",
    title: "Proverbs 3",
    subtitle: "Hawaiian idioms and wisdom",
    accent: "ocean",
    cards: [
      {
        front: "Ike i ke au nui, me ke au iki.",
        back: "Know the big currents and the little currents.",
      },
      {
        front: "A'ohe hana nui ke alu 'ia.",
        back: "No task is too big when done together by all.",
      },
      {
        front: "He ali'i ka 'āina; he kauwā ke kanaka.",
        back: "The land is chief; people are its servants.",
      },
      {
        front: "I ka 'ōlelo no ke ola, i ka 'ōlelo no ka make.",
        back: "In speech there is life; in speech there is death.",
      },
      {
        front: "Nānā ka maka; ho'olohe ka pepeiao; pa'a ka waha.",
        back: "Observe with the eyes, listen with the ears, and close the mouth.",
      },
      {
        front: "Mālama i ke kai, a mālama ke kai iā 'oe.",
        back: "Care for the sea, and the sea will care for you.",
      },
      {
        front: "Hahai nō ka ua i ka ululā'au.",
        back: "The rain follows the forest.",
      },
      {
        front: "He wa'a he moku, he moku he wa'a.",
        back: "The canoe is an island; the island is a canoe.",
      },
      {
        front: "E nānā i ke kumu.",
        back: "Look to the source.",
      },
      {
        front: "Pūpūkahi i holomua.",
        back: "Unite in order to move forward.",
      },
    ],
  },
  {
    id: "plants-1",
    title: "Plants 1",
    subtitle: "Plants of Hawai'i",
    accent: "ocean",
    cards: [
      { front: "Kalo", back: "Taro; foundational staple and sacred elder sibling in Hawaiian tradition." },
      { front: "ʻUlu", back: "Breadfruit; major canoe plant and important food source." },
      { front: "Niu", back: "Coconut; provides food, fiber, oil, and materials for daily life." },
      { front: "ʻUhala", back: "Hala (pandanus); leaves woven into mats, sails, and lei." },
      { front: "Kukui", back: "Candlenut tree; state tree, source of light, medicine, and dye." },
      { front: "Kī", back: "Ti plant; used for protection, ceremony, food wrapping, and medicine." },
      { front: "Maiʻa", back: "Banana; versatile canoe plant with many traditional cultivars." },
      { front: "ʻAwapuhi", back: "Shampoo ginger; valued medicinally and for body care." },
      { front: "ʻAwa", back: "Kava; ceremonial plant used for calming and social rituals." },
      { front: "ʻOlena", back: "Turmeric; medicine, food coloring, and ceremonial use." },
      { front: "Koa", back: "Acacia koa; prized hardwood for canoes, tools, and carving." },
      { front: "ʻŌhiʻa lehua", back: "Keystone native tree linked to forest and watershed health." },
      { front: "Lauaʻe", back: "Fragrant fern used in lei-making and cultural adornment." },
      { front: "Naupaka", back: "Coastal and mountain shrub featured in moʻolelo and lei." },
      { front: "ʻIlima", back: "Native flower associated with lei and chiefly tradition." },
    ],
  },
  {
    id: "practice-1",
    title: "Practice Aloha",
    subtitle: "Ohana values and healing practices",
    accent: "ocean",
    cards: [
      { front: "Ohana", back: "The importance of the family." },
      { front: "Kupuna", back: "Respect for seniors and elders." },
      {
        front: "Hooponopono",
        back: "Ensuring harmonious interdependence within the ohana through regular family therapy.",
      },
      { front: "Mahiki", back: "Dealing with each successive layer of trouble." },
      { front: "Mihi", back: "Forgiving fully and completely." },
      { front: "Kala", back: "Freeing each other completely." },
    ],
  },
];
